FROM openjdk:8

MAINTAINER jeecgos@163.com

RUN mkdir -p /jeecg-boot

WORKDIR /jeecg-boot

ADD jeecg-boot-module-system-2.2.1.jar jeecg-boot-module-system-2.2.1.jar

EXPOSE 8081

CMD java -jar jeecg-boot-module-system-2.2.1.jar